# -*- coding: utf-8 -*-
"""Natalia_Amaral_aula4Pratico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-q4Rnkgu2s7lHTyVQxQhiulLxwLaUwTo
"""



"""Código do jogo Wumpus"""

# FONTES:
# https://github.com/jdramirezl/WumpusWorldAI
# auxílio do Gemini

import random

# para guardar o que cada uma das posições contem
class posicao:
    def __init__(self):
        # no comeco, todas as casas estao vazias
        self.tem_wumpus = False
        self.tem_abismo = False
        self.tem_ouro = False
        self.tem_brisa = False
        self.tem_fedor = False
        self.visitada = False # para poder ir imprimindo o que tem em cada casa conforme o jogador descubra

#inicializa o tabuleiro com tamanho 4x4
tamanho = 4
tabuleiro = []

for i in range(tamanho):
    linha = []
    for j in range(tamanho):
        linha.append(posicao())
    tabuleiro.append(linha)

# o nosso jogador começa na posição 0,0 e o wumpus, buraco ou ouro nao podem estar nessa posição.
posicoes_livres = []
for i in range(tamanho):
    for j in range(tamanho):
        if i == 0 and j == 0:
            continue
        posicoes_livres.append((i, j))

# sorteia uma posição para o wumpus, 3 para os buracos e 1 para o ouro. Nessa implementação, o ouro não pode estar na mesma casa que o Wumpus.
elementos = random.sample(posicoes_livres, 5)

pos_wumpus = elementos[0]
pos_ouro = elementos[4]

tabuleiro[pos_wumpus[0]][pos_wumpus[1]].tem_wumpus = True
tabuleiro[pos_ouro[0]][pos_ouro[1]].tem_ouro = True

for i in range(1, 4):
    linha_abismo = elementos[i][0]
    coluna_abismo = elementos[i][1]
    tabuleiro[linha_abismo][coluna_abismo].tem_abismo = True

# brisa e fedor
def espalhar_percepcoes(linha, coluna, tipo):
    vizinhos = [
        (linha - 1, coluna),
        (linha + 1, coluna),
        (linha, coluna - 1),
        (linha, coluna + 1)
    ]
    for l, c in vizinhos: # para não ultrapassar as 16 posições
        if 0 <= l < tamanho and 0 <= c < tamanho:
            if tipo == 'W':
                tabuleiro[l][c].tem_fedor = True
            elif tipo == 'A':
                tabuleiro[l][c].tem_brisa = True

espalhar_percepcoes(pos_wumpus[0], pos_wumpus[1], 'W')

for i in range(1, 4):
    espalhar_percepcoes(elementos[i][0], elementos[i][1], 'A')

# inicia as variáveis do jogador
linha_jogador = 0
coluna_jogador = 0
pontos = 0
flechas = 1
ouro_mochila = False
jogo_rodando = True
wumpus_vivo = True

# loop do jogo
print("----------------------------------------Iniciando o mundo do Wumpus!!!-------------------------------------")
print("Comandos: 'w' (cima), 's' (baixo), 'a' (esquerda), 'd' (direita)', 'p' (pegar ouro), 't' (atirar flecha), 'e' (escalar saída)")

while jogo_rodando:
    # revela no mapa a posição que o jogador descobrir
    posicao_atual = tabuleiro[linha_jogador][coluna_jogador]
    posicao_atual.visitada = True

    # desenha o tabuleiro
    for i in range(tamanho):
        linha_str = ""
        for j in range(tamanho):
            # Se a casa não foi visitada e o jogador não está nela, mostra [ ? ]
            if not tabuleiro[i][j].visitada and not (i == linha_jogador and j == coluna_jogador):
                linha_str += "[ ? ]".ljust(22)
            else:
                # Se foi visitada, vamos listar tudo que tem dentro dela
                itens = []
                if i == linha_jogador and j == coluna_jogador: itens.append("J") # O jogador
                if tabuleiro[i][j].tem_wumpus: itens.append("Wumpus")
                if tabuleiro[i][j].tem_abismo: itens.append("Buraco")
                if tabuleiro[i][j].tem_ouro: itens.append("Ouro")
                if tabuleiro[i][j].tem_brisa: itens.append("Brisa")
                if tabuleiro[i][j].tem_fedor: itens.append("Fedor")

                # Se a lista estiver vazia, imprime [ livre ]
                if len(itens) == 0:
                    linha_str += "[ livre ]".ljust(22)
                else:
                    # Junta as palavras com vírgula e alinha o texto com ljust
                    texto = "[" + ",".join(itens) + "]"
                    linha_str += texto.ljust(22)

        print(linha_str)
        print() # Adiciona uma quebra de linha para o mapa não ficar tão espremido

    # mostra o status do jogador
    pos_visual_linha = linha_jogador + 1
    pos_visual_coluna = coluna_jogador + 1
    print(f"Posição atual: [{pos_visual_linha}, {pos_visual_coluna}] | Pontos: {pontos} | Flechas: {flechas}")

    # se o jogador entrar numa casa que tenha o wumpus ou buraco, ele morre
    if posicao_atual.tem_wumpus and wumpus_vivo:
        print("Que pena! O wumpus te matou...Fim de jogo")
        pontos -= 100
        print(f"Pontuação final: {pontos}")
        break

    if posicao_atual.tem_abismo:
        print("Que pena! Você caiu em um buraco! Mais atenção na próxima vez")
        pontos -= 100
        print(f"Pontuação final: {pontos}")
        break

    # verifica as percepções da posição atual
    percepcoes = []
    if posicao_atual.tem_brisa: percepcoes.append("Você sente uma brisa gelada.")
    if posicao_atual.tem_fedor: percepcoes.append("Você sente um fedor horrível.")
    if posicao_atual.tem_ouro: percepcoes.append("Você vê um brilho no chão!")

    if len(percepcoes) > 0:
        for p in percepcoes:
            print(p)
    else:
        print("Nada diferente nessa posição")

    # verifica o que o usuário deseja fazer
    acao = input("\nO que deseja fazer? ").lower()
    pontos -= 1

    # movimentos do jogador
    if acao == 'w':
        if linha_jogador > 0: linha_jogador -= 1
        else: print("Você foi de encontro com a parede!!! Ai!")
    elif acao == 's':
        if linha_jogador < tamanho - 1: linha_jogador += 1
        else: print("Você foi de encontro com a parede!!! Ai!")
    elif acao == 'a':
        if coluna_jogador > 0: coluna_jogador -= 1
        else: print("Você foi de encontro com a parede!!! Ai!")
    elif acao == 'd':
        if coluna_jogador < tamanho - 1: coluna_jogador += 1
        else: print("Você foi de encontro com a parede!!! Ai!")

    # movimento pegar_ouro
    elif acao == 'p':
        if posicao_atual.tem_ouro:
            print("Você pegou o ouro!! UHULL!")
            posicao_atual.tem_ouro = False
            ouro_mochila = True
        else:
            print("Não tem ouro aqui")

    # atirar a flecha
    elif acao == 't':
        if flechas > 0:
            flechas -= 1
            print("Você atirou sua flecha...")

            # Verifica as casas adjacentes ao Wumpus
            vizinhos_wumpus = [
                (pos_wumpus[0] - 1, pos_wumpus[1]), # cima
                (pos_wumpus[0] + 1, pos_wumpus[1]), # baixo
                (pos_wumpus[0], pos_wumpus[1] - 1), # esquerda
                (pos_wumpus[0], pos_wumpus[1] + 1)  # direita
            ]

            # O Wumpus só morre se atirar de uma dessas casas adjacentes
            if (linha_jogador, coluna_jogador) in vizinhos_wumpus:
                print("Você ouve um grito assustador! O Wumpus está morto!")
                wumpus_vivo = False
                pontos += 50
                tabuleiro[pos_wumpus[0]][pos_wumpus[1]].tem_wumpus = False
            else:
                print("Você errou o tiro...Gastou sua única flecha!")
        else:
            print("Não há mais flechas para serem usadas")

    # escalar caverna
    elif acao == 'e':
        # o jogador só pode escalar se estiver na posição 0,0
        if linha_jogador == 0 and coluna_jogador == 0:
            if ouro_mochila:
                pontos += 50
                print(f"Parabens!!!! Você venceu o Wumpus e pegou o ouro!!")
                print(f"Pontuação final: {pontos}")
                jogo_rodando = False
            else:
                print("Está com medo? Volte lá e pegue o ouro!")
        else:
            print("Você não pode escalar aqui, somente no início")

    else:
        print("Comando inválido. Tente: w, a, s, d, p, t, e")